#!/usr/bin/env python
# coding: utf8
#from gluon import *

#!/usr/bin/env python
# coding: utf8
# request, response, session, cache, T, db(s)
# must be passed and cannot be imported!

from collections import namedtuple, OrderedDict


def replace_stars(data):
    for i, v in enumerate(data):
        for i2, v2 in enumerate(v):
            if isinstance(v2, str) and "*" in v2:
                data[i][i2] = v2.replace("*", data[i][data[0].index("parent")])

converted = ['attributes', 'bodyparts', 'stats', 'skill_attribmods']

states = ["Physical Damage",
          "Stun Damage",
          "Head Wounds",
          "Upper Body Wounds",
          "Lower Body Wounds",
          "Left Arm Wounds",
          "Right Arm Wounds",
          "Left Leg Wounds",
          "Right Leg Wounds",
          "Stunned",
          "Unconscious"]

permits = [
    ["name", "cost_multiplier"],
    ['none', 1],
    ['security', 2],
    ['military', 5]
]

permits_nt = namedtuple('permits', ['id'] + permits[0])
permits_dict = OrderedDict([(entry[0], permits_nt(*([i] + entry))) for i, entry in enumerate(permits[1:])])

damagekinds = [
    ["name", "healing_time", "description", "priority"],
    ["fatigue", 1 / 2.4, "Damage gained by physical exertion", 1],
    ["stun", 10, "Bruises,...", 10],
    ["physical", 600, "", 100],
    ["drain stun", 5, "Drain Stun", 5],
    ["drain physical", 200, "Drain Physical", 50]
]

damagekinds_nt = namedtuple('damagekind', ['id'] + damagekinds[0])
damagekinds_dict = OrderedDict([(entry[0], damagekinds_nt(*([i] + entry))) for i, entry in enumerate(damagekinds[1:])])

statclasses = [
    ["name", "parent"],
    ["Char", None],
    ["Item", None],
    ["Attributes", "Char"],
    ["Ware", "Item"],
    ["Cyberware", "Ware"],
    ["Bioware", "Ware"],
    ["Nanoware", "Ware"],
    ["Genetech", "Ware"],
    ["Weapon", "Item"],
    ["Ranged Weapon", "Weapon"],
    ["Melee Weapon", "Weapon"],
    ["Armor", "Item"],
    ["Sensor", "Item"],
    ["Cyberdeck", "Item"]
]

stats = [
    ["name", "clas", "parent", "type"],
    ["Action Costs", "Char", None, "float"],
    ["Awareness Costs", "Char", "Action Costs", "float"],
    ["Time Costs", "Char", "Action Costs", "float"],
    ["Physical Awareness", "Char", "Awareness Costs", "float"],
    ["Physical Time", "Char", "Time Costs", "float"],
    ["Move Awareness", "Char", "Physical Awareness Costs", "float"],
    ["Move Time", "Char", "Physical Time Costs", "float"],
    ["Shift Awareness", "Char", "Physical Awareness Costs", "float"],
    ["Shift Time", "Char", "Physical Time Costs", "float"],
    ["Meta Awareness", "Char", "Awareness Costs", "float"],
    ["Meta Time", "Char", "Time Costs", "float"],
    ["General Awareness", "Char", "Awareness Costs", "float"],
    ["General Time", "Char", "Time Costs", "float"],
    ["Combat Awareness", "Char", "Physical Awareness Costs", "float"],
    ["Combat Time", "Char", "Physical Time Costs", "float"],
    ["Melee Combat Awareness", "Char", "Combat Awareness", "float"],
    ["Melee Combat Time", "Char", "Combat Time", "float"],
    ["Ranged Combat Awareness", "Char", "Combat Awareness", "float"],
    ["Ranged Combat Time", "Char", "Combat Time", "float"],
    ["Astral Awareness", "Char", "Awareness Costs", "float"],
    ["Astral Time", "Char", "Time Costs", "float"],
    ["Matrix Awareness", "Char", "Awareness Costs", "float"],
    ["Matrix Time", "Char", "Time Costs", "float"],
    ["Name", "Char", None, "str"],
    ["Streetname", "Char", None, "str"],
    ["Date of Birth", "Char", None, "date"],
    ["Skintone", "Char", None, "str"],
    ["Eyecolor", "Char", None, "str"],
    ["Hairstyle", "Char", None, "str"],
    ["Haircolor", "Char", None, "str"],
    ["Loadout", "Char", None, "int"],
    ["Woundlimit", "Char", None, "float"],
    ["Life", "Char", None, "float"],
    ["Carriing Capacity", "Char", None, "float"],
    ["Initiative", "Char", None, "float"],
    ["Reaction", "Char", None, "float"],
    ["Physical Initiative", "Char", "Initiative", "float"],
    ["Physical Reaction", "Char", "Reaction", "float"],
    ["Matrix Initiative", "Char", "Initiative", "float"],
    ["Matrix Reaction", "Char", "Reaction", "float"],
    ["Astral Initiative", "Char", "Initiative", "float"],
    ["Astral Reaction", "Char", "Reaction", "float"],
    ["Legality", "Item", None, "float"],
    ["Visible Stealth Rating", "Item", None, "float"],
    ["Scan Stealth Rating", "Item", None, "float"],
    ["Ballistic Armor", "Armor", None, "float"],
    ["Impact Armor", "Armor", None, "float"],
    ["Shielding", "Armor", None, "float"],
    ["Insulation", "Armor", None, "float"],
    ["Agility Cap", "Armor", None, "float"],
    ["Coordination Multiplier", "Armor", None, "float"],
    ["Damage", "Weapon", None, "float"],
    ["Damagetype", "Weapon", None, "str"],
    ["Penetration", "Weapon", None, "float"],
    ["Range", "Weapon", None, "float"],
    ["Single Shot Rate", "Weapon", None, "integer"],
    ["Burst Shot Rate", "Weapon", None, "integer"],
    ["Auto Shot Rate", "Weapon", None, "integer"],
]

stats_nt = namedtuple('stat', ['id'] + stats[0])
stats_dict = OrderedDict([(entry[0], stats_nt(*([i] + entry))) for i, entry in enumerate(stats[1:])])

races = [ ["name", "Size", "Weight", "Agility", "Constitution", "Coordination", "Strength", "Charisma", "Intuition", "Logic",
           "Willpower", "Magic", "xpcost"],
            ["Human", 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
            ["Troll", 1.33, 1.33, 0.9, 1.33, 0.67, 1.1, 0.83, 1.33, 0.67, 0.67, 1, 0],
            ["Orc", 1.1, 1.33, 1.2, 1.33, 1, 1.2, 0.67, 1.17, 0.67, 1.33, 1, 0],
            ["Elf", 1.1, 0.8, 1.40, 0.9, 1.17, 0.8, 1.17, 1, 1, 1, 1, 0],
            ["Dwarf", 0.75, 1.4, 0.8, 1.33, 1.17, 1.5, 1, 1, 1, 1, 1, 0],
]

races_nt = namedtuple('race', ['id'] + races[0])
races_dict = OrderedDict([(entry[0], races_nt(*([i] + entry))) for i, entry in enumerate(races[1:])])

gendermods = [
   ["name", "Size", "Weight", "Agility", "Constitution", "Coordination", "Strength", "Charisma", "Intuition", "Logic",
           "Willpower", "Magic"],
    ["Male", 1.05, 1, 1, 1, 1, 1.05, 0.9, 1, 1, 1, 1],
    ["Female", 0.95, 1, 1, 1, 1, 0.95, 1.1, 1, 1, 1, 1],
]

gendermods_nt = namedtuple('gendermod', ['id'] + gendermods[0])
gendermods_dict = OrderedDict([(entry[0], gendermods_nt(*([i] + entry))) for i, entry in enumerate(gendermods[1:])])

attributes = [
    ["name", "base", "description", "factor", "kind"],
    ["Agility", 30, "speed of muscle movement, dexterity of limbs..", 10000, "physical"],
    ["Constitution", 30, "ability to endure fatigue, bodily toughness, resitance to poinson and disease", 10000, "physical"],
    ["Coordination", 30, "ability to coordinate agility and strength", 10000, "physical"],
    ["Size", 1.75, "size of a character in meteres", 100000, "physical"],
    ["Strength", 30, "raw physical strength", 10000, "physical"],
    ["Weight", 75, "weight of the character in kg", -10000, "physical"],
    ["Charisma", 30, "empathy, ability to influence others", 10000, "mental"],
    ["Intuition", 30, "unconsciousness thinking, ability to recognize patterns", 10000, "mental"],
    ["Logic", 30, "raw mental processing power", 10000, "mental"],
    ["Willpower", 30, "ability to resist temptations and influence of others", 10000, "mental"],
    ["Magic", 30, "the ability to channel magic", 20000, "special"],
]


attributes_nt = namedtuple('attribute', ['id'] + attributes[0])
attributes_dict = OrderedDict([(entry[0], attributes_nt(*([i] + entry))) for i, entry in enumerate(attributes[1:])])

skills = [
    ["name", "parent", "expweight"],
    ["Combat", None, 1],
    ["Armed Combat", "Combat", 1],
    ["Impact Weapons", "Armed Combat", 1],
    ["Piercing Weapons", "Armed Combat", 1],
    ["Slashing Weapons", "Armed Combat", 1],
    ["Unarmed Combat", "Combat", 1],
    ["Brawling", "Unarmed Combat", 1],
    ["Wrestling", "Unarmed Combat", 1],
    ["Thrown Weapons", "Combat", 1],
    ["Aerodynamics", "Thrown Weapons", 1],
    ["Axes", "Thrown Weapons", 1],
    ["Balls", "Thrown Weapons", 1],
    ["Ranged Weapons", "Combat", 1],
    ["Archery", "Ranged Weapons", 1],
    ["Pistols", "Ranged Weapons", 1],
    ["Automatics", "Ranged Weapons", 1],
    ["Long Rifle", "Ranged Weapons", 1],
    ["Indirect Fire", "Ranged Weapons", 1],
    ["Launch Weapons", "Ranged Weapons", 1],
    ["Spray Weapons", "Ranged Weapons", 1],
    ["Physical", None, 1],
    ["Acrobatics", "Physical", 1],
    ["Balance", "Acrobatics", 1],
    ["Dodge", "Acrobatics", 1],
    ["Athletics", "Physical", 1],
    ["Climbing", "Athletics", 1],
    ["Jumping", "Athletics", 1],
    ["Lifting", "Athletics", 1],
    ["Running", "Athletics", 1],
    ["Swimming", "Athletics", 1],
    ["Carouse", "Physical", 1],
    ["Perform", "Physical", 1],
    ["Dancing", "Perform", 1],
    ["Singing", "Perform", 1],
    ["Stealth", "Physical", 1],
    ["Hideing", "Stealth", 1],
    ["Shadowing", "Stealth", 1],
    ["Sneaking", "Stealth", 1],
    ["Sleight of Hand", "Physical", 1],
    ["Lockpicking", "Sleight of Hand", 1],
    ["Pickpocketing", "Sleight of Hand", 1],
    ["Quickdrawing", "Sleight of Hand", 1],
    ["Processing", None, 1],
    ["Art", "Processing", 1],
    ["Painting", "Art", 1],
    ["Sculpting", "Art", 1],
    ["Composure", "Processing", 1],
    ["Mental Composure", "Composure", 1],
    ["Physical Composure", "Composure", 1],
    ["Memory", "Processing", 1],
    ["Navigation", "Processing", 1],
    ["Orientation", "Navigation", 1],
    ["Land", "Navigation", 1],
    ["Sea", "Navigation", 1],
    ["Space", "Navigation", 1],
    ["Air", "Navigation", 1],
    ["Perception", "Processing", 1],
    ["Aural", "Perception", 1],
    ["Olfactorial", "Perception", 1],
    ["Tactile", "Perception", 1],
    ["Visual", "Perception", 1],
    ["Askenning", "Perception", 1],
    ["Judge Person", "Processing", 1],
    ["Guess Intentions", "Processing", 1],
    ["Detect Deceit", "Judge Person", 1],
    ["Interrogation", "Judge Person", 1],
    ["Forecast Behaviour", "Judge Person", 1],
    ["Empathy", None, 1],
    ["Act", "Empathy", 1],
    ["Theatrical", "Act", 1],
    ["Impersonation", "Act", 1],
    ["Animal Controll", "Empathy", 1],
    ["Animal Training", "Animal Controll", 1],
    ["Animal Riding", "Animal Controll", 1],
    ["Discussion", "Empathy", 1],
    ["Convince", "Discussion", 1],
    ["Instruction", "Discussion", 1],
    ["Negotiation", "Discussion", 1],
    ["Interaction", "Empathy", 1],
    ["Deception", "Interaction", 1],
    ["Intimidation", "Interaction", 1],
    ["Leadership", "Interaction", 1],
    ["Persuasion", "Interaction", 1],
    ["Oratory", "Interaction", 1],
    ["Magic", None, 1],
    ["Spellcasting", "Magic", 1],
    ["Spellslinging", "Spellcasting", 1],
    ["Ritual Magic", "Spellcasting", 1],
    ["Invocation", "Magic", 1],
    ["Binding", "Invocation", 1],
    ["Banishing", "Invocation", 1],
    ["Summoning", "Invocation", 1],
    ["Alchemy", "Magic", 1],
    ["Matrix", None, 1],
    ["Computers", "Matrix", 1],
    ["Data Search", "Computers", 1],
    ["Programming", "Computers", 1],
    ["Computer Use", "Computers", 1],
    ["Hacking", "Matrix", 1],
    ["Cracking", "Hacking", 1],
    ["Cybercombat", "Hacking", 1],
    ["Decryption", "Hacking", 1],
    ["Security", "Hacking", 1],
    ["Technical", None, 1],
    ["Chemistry", "Technical", 1],
    ["Toxins", "Chemistry", 1],
    ["Demolitions", "Chemistry", 1],
    ["Electronics", "Technical", 1],
    ["Maglocks", "Electronics", 1],
    ["Sensors", "Electronics", 1],
    ["Optical Computers", "Electronics", 1],
    ["Electronics Warfare", "Electronics", 1],
    ["Mechanics", "Technical", 1],
    ["Locks", "Mechanics", 1],
    ["Ground Vehicles", "Mechanics", 1],
    ["Airborne Vehicles", "Mechanics", 1],
    ["Spacecraft", "Mechanics", 1],
    ["Watercraft", "Mechanics", 1],
    ["Weapons", "Mechanics", 1],
    ["Traps", "Mechanics", 1],
    ["Medics", "Technical", 1],
    ["Cybernetics", "Medics", 1],
    ["Extended Care", "Medics", 1],
    ["First Aid", "Medics", 1],
    ["Pilot", "Technical", 1],
    ["Airplane", "Pilot", 1],
    ["Hovercraft", "Pilot", 1],
    ["Helicopter", "Pilot", 1],
    ["Submarine", "Pilot", 1],
    ["Thrust", "Pilot", 1],
    ["Boat", "Pilot", 1],
    ["Wheeled", "Pilot", 1],
    ["Social", "Technical", 1],
    ["Disguise", "Social", 1],
]

skills_nt = namedtuple('skill', ['id'] + skills[0])
skills_dict = OrderedDict([(entry[0], skills_nt(*([i] + entry))) for i, entry in enumerate(skills[1:])])

skill_attribmods = [['skill', 'Agility', 'Constitution', 'Coordination', 'Strength', 'Weight',
                     'Charisma', 'Intuition', 'Logic', 'Willpower', 'Magic', 'Size'],
                    ["Combat", 0.25, 0, 0.25, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Armed Combat", 1., 0, 0.25, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Impact Weapons", 1., 0, 0.25, 0, 0, 0, 0., 0, 0, 0, 0],
                    ["Piercing Weapons", 1., 0, 0.25, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Slashing Weapons", 1., 0, 0.25, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Unarmed Combat", 1., 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Brawling", 1., 0, 0.25, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Wrestling", 1., 0, 0.75, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Thrown Weapons", 0.5, 0, 0.75, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Aerodynamics", 0.5, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Axes", 0.5, 0, 1., 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Balls", 0.25, 0, 0.5, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Ranged Weapons", 0.25, 0, 0.75, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Archery", 0.5, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Pistols", 0.125, 0, 0.5, 0, 0, 0, 0.125, 0, 0, 0, 0],
                    ["Automatics", 0, 0, 0.5, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Long Rifle", 0, 0, 0.25, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Indirect Fire", 0, 0, 0.25, 0, 0, 0, 0.25, 0.25, 0, 0, 0],
                    ["Launch Weapons", 0, 0, 0, 0, 0, 0, 0.25, 0.25, 0, 0, 0],
                    ["Spray Weapons", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Physical", 1., 0, 1., 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Acrobatics", 1.5, 0, 0.5, 1, -1, 0, 0, 0, 0, 0, 0],
                    ["Balance", 1.5, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Dodge", 1.5, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Athletics", 0.5, 0, 0.5, 1, -1, 0, 0, 0, 0, 0, 0],
                    ["Climbing", 0, 0.5, 0.5, 1.5, -1.5, 0, 0, 0, 0, 0, 0],
                    ["Jumping", 0.5, 0, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0],
                    ["Lifting", 0, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Running", 0, 1, 0.25, 1, -1, 0, 0, 0, 0, 0, 0],
                    ["Swimming", 0, 1, 0.25, 1, -1, 0, 0, 0, 0, 0, 0],
                    ["Carouse", 0, 1.5, 0, 0, 0.5, 0, 0, 0, 0, 0, 0],
                    ["Perform", 0, 0, 0, 0.25, 0, 1., 0, 0, 0, 0, 0],
                    ["Dancing", 0, 0, 0, 0.5, 0, 0.5, 0, 0, 0, 0, 0],
                    ["Singing", 0, 0, 0, 0.25, 0, 0.75, 0, 0, 0, 0, 0],
                    ["Stealth", 0, 0, 1.25, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Hideing", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Shadowing", 0, 0, 0.75, 0, 0, 0, 0.75, 0, 0, 0, 0],
                    ["Sneaking", 0, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Sleight of Hand", 0.5, 0, 0.75, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Lockpicking", 0.5, 0, 0.75, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Pickpocketing", 0.5, 0, 0.5, 0, 0, 0, 0.25, 0, 0, 0, 0],
                    ["Quickdrawing", 0.75, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["Processing", 0, 0, 0, 0, 0, 0, 1.5, 0, 0, 0, 0],
                    ["Art", 0, 0, 1., 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Painting", 0, 0, 1., 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Sculpting", 0, 0, 1., 0, 0, 0, 0.5, 0, 0, 0, 0],
                    ["Composure", 0, 0, 0.5, 0, 0, 0, 0., 0, 1.5, 0, 0],
                    ["Mental Composure", 0, 0, 0, 0, 0, 0, 0., 0, 2, 0, 0],
                    ["Physical Composure", 0, 0, 1.0, 0, 0, 0, 0., 0, 1., 0, 0],
                    ["Memory", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 0, 0],
                    ["Navigation", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Orientation", 0, 0, 0, 0, 0, 0, 1., 0.25, 0, 0, 0],
                    ["Land", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Sea", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Space", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Air", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Perception", 0, 0, 0, 0, 0, 0, 1.25, 0, 0, 0, 0],
                    ["Aural", 0, 0, 0, 0, 0, 0, 1.25, 0, 0, 0, 0],
                    ["Olfactorial", 0, 0, 0, 0, 0, 0, 1.25, 0, 0, 0, 0],
                    ["Tactile", 0, 0, 0, 0, 0, 0, 1.25, 0, 0, 0, 0],
                    ["Visual", 0, 0, 0, 0, 0, 0, 1.25, 0, 0, 0, 0],
                    ["Askenning", 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 1., 0],
                    ["Judge Person", 0, 0, 0, 0, 0, 0, .75, 0.25, 0, 0, 0],
                    ["Guess Intentions", 0, 0, 0, 0, 0, 0, .5, 0.5, 0, 0, 0],
                    ["Detect Deceit", 0, 0, 0, 0, 0, 0, .5, 0.5, 0, 0, 0],
                    ["Interrogation", 0, 0, 0, 0, 0, 0, .25, 0.75, 0, 0, 0],
                    ["Forecast Behaviour", 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
                    ["Empathy", 0, 0, 0, 0, 0, 1.5, 0, 0, 0, 0, 0],
                    ["Act", 0, 0, 0.5, 0, 0, 1., 0, 0, 0, 0, 0],
                    ["Theatrical", 0, 0, 0.25, 0, 0, 1., 0, 0.25, 0, 0, 0],
                    ["Impersonation", 0, 0, 0, 0, 0, 1., 0.5, 0, 0, 0, 0],
                    ["Animal Controll", 0, 0, 0, 0, 0, 1., 0.25, 0, 0, 0, 0],
                    ["Animal Training", 0, 0, 0, 0, 0, 1., 0.5, 0, 0, 0, 0],
                    ["Animal Riding", 0, 0, 0.5, 0, 0, 0.5, 0.5, 0, 0, 0, 0],
                    ["Discussion", 0, 0, 0, 0, 0, 1.5, 0, 0.5, 0, 0, 0],
                    ["Convince", 0, 0, 0, 0, 0, 1.0, 0, 1.0, 0, 0, 0],
                    ["Instruction", 0, 0, 0, 0, 0, 0.5, 0, 1.0, 0, 0, 0],
                    ["Negotiation", 0, 0, 0, 0, 0, 0.5, 0, 0.5, 1.0, 0, 0],
                    ["Interaction", 0, 0, 0, 0, 0, 1.0, 0.25, 0, 0, 0, 0],
                    ["Deception", 0, 0, 0, 0, 0, 1.5, 0.5, 0, 0, 0, 0],
                    ["Intimidation", 0, 0, 0, 0, 0, 1., 0, 0, 0, 1.0, 0],
                    ["Leadership", 0, 0, 0, 0, 0, 1.5, 0.5, 0, 0, 0, 0],
                    ["Persuasion", 0, 0, 0, 0, 0, 1.5, 0.25, 0.25, 0, 0, 0],
                    ["Oratory", 0, 0, 0, 0, 0, 1.5, 0, 0.5, 0, 0, 0],
                    ["Magic", 0, 0, 0, 0, 0, 0, 0, 0, 0, 2., 0],
                    ["Spellcasting", 0, 0, 0, 0, 0, 0, 0.25, 0.75, 0, 1., 0],
                    ["Spellslinging", 0, 0, 0, 0, 0, 0, 0.25, 0.75, 0, 1., 0],
                    ["Ritual Magic", 0, 0, 0, 0, 0, 0, 0., 1., 0, 1., 0],
                    ["Invocation", 0, 0, 0, 0, 0, 1., 0, 0, 0, 1., 0],
                    ["Binding", 0, 0, 0, 0, 0, 0.5, 0, 0, 0.5, 1., 0],
                    ["Banishing", 0, 0, 0, 0, 0, 0.5, 0, 0, 0.5, 1., 0],
                    ["Summoning", 0, 0, 0, 0, 0, 1., 0, 0, 0, 1., 0],
                    ["Alchemy", 0, 0, 0, 0, 0, 0, 0, 1., 0, 0.5, 0],
                    ["Matrix", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Computers", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Data Search", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Programming", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Computer Use", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Hacking", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Cracking", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Cybercombat", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Decryption", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Security", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Technical", 0, 0, 0, 0, 0, 0, 0., 1., 0, 0., 0],
                    ["Chemistry", 0, 0, 0.35, 0, 0, 0, 0, 1., 0, 0., 0],
                    ["Toxins", 0, 0, 0.25, 0, 0, 0, 0, 1., 0, 0., 0],
                    ["Demolitions", 0, 0, 0.5, 0, 0, 0, 0, 0.75, 0, 0., 0],
                    ["Electronics", 0, 0, 0.5, 0, 0, 0, 0, 0.75, 0, 0., 0],
                    ["Locks", 0, 0, 0.5, 0, 0, 0, 0, 0.75, 0, 0., 0],
                    ["Sensors", 0, 0, 0.5, 0, 0, 0, 0, 0.75, 0, 0., 0],
                    ["Computers", 0, 0, 0.5, 0, 0, 0, 0, 0.75, 0, 0., 0],
                    ["Electronics Warfare", 0, 0, 0, 0, 0, 0, 0, 1., 0, 0., 0],
                    ["Mechanics", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Locks", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Ground Vehicles", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Airborne Vehicles", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Spacecraft", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Watercraft", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Weapons", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Traps", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Medics", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Cybernetics", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Extended Care", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["First Aid", 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0., 0],
                    ["Pilot", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Airplane", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Hovercraft", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Helicopter", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Submarine", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Thrust", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Watercraft", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Wheeled", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Social", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0],
                    ["Disguise", 0, 0, 0.5, 0, 0, 0, 0.5, 0, 0, 0., 0]
]

skill_attribmods_nt = namedtuple('skill_attribmod', ['id'] + skill_attribmods[0])
skills_attribmods_dict = OrderedDict([(entry[0], skill_attribmods_nt(*([i] + entry))) for i, entry in enumerate(skill_attribmods[1:])])

actions = [
    ["name", "category", "awareness", "time_val", "a_limit", "t_limit", "ongoing"],
    ["Walk", "move", 3, -3, 1.5, 1.5, False],
    ["Run", "move", 6, -3, 1.5, 1.5, True],
    ["Sprint", "move", 10, -3, 1.5, 1.5, True],
    ["Jump", "move", 8, -3, 1.5, 1.5, False],
    ["Climb", "move", 15, -1, 1.5, 1.5, False],
    ["Swim", "move", 7, -1, 1.5, 1.5, False],
    ["Crouch Walk", "move", 4, -3, 1.5, 1.5, False],
    ["Crawl", "move", 10, -1, 1.5, 1.5, False],

    ["Crouch", "shift", 3, .5, 1.5, 1.5, False],
    ["Stand", "shift", 2, 1.0, 1.5, 1.5, False],
    ["Stand Up", "shift", 10, 3.0, 1.5, 1.5, False],
    ["Jumpg Up", "shift", 30, 1.0, 1.5, 1.5, False],
    ["Drop Down", "shift", 30, .5, 1.5, 1.5, False],
    ["Get Down", "shift", 10, 2.0, 1.5, 1.5, False],
    ["Turn", "shift", 1, .3, 1.5, 1.5, False],
    ["Peek", "shift", 5, .5, 1.5, 1.5, False],
    ["Take Cover", "shift", 5, .5, 1.5, 1.5, False],

    ["Interrupt", "meta", 5, 0, 1.5, 1.5, False],
    ["Postpone", "meta", 0, 0, 1.5, 1.5, False],
    ["Delay", "meta", 0, 0, 1.5, 1.5, False],
    ["Overwatch", "meta", 10, 0, 1.5, 1.5, False],


    ["Melee Attack", "melee combat", -2, -2, 1.5, 1.5, False],
    ["Parry", "melee combat", -2, -2, 1.5, 1.5, False],

    ["Single Shot", "ranged combat", 10, -2, 1.5, 1.5, False],
    ["Burst Shot", "ranged combat", 15, -2, 1.5, 1.5, False],
    ["Full Auto Shot", "ranged combat", 20, -1, 1.5, 1.5, True],
    ["Brace Weapon", "ranged combat", 5, .5, 1.5, 1.5, False],
    ["Throw Weapon", "ranged combat", -2, -2, 1.5, 1.5, False],
    ["Evasive Actions", "ranged combat", 5, 0, 1.5, 1.5, False],

    ["Target", "ranged combat", 5, 0.2, 1.5, 1.5, False],
    ["Sight", "ranged combat", 5, 0.5, 1.5, 1.5, False],
    ["Aim", "ranged combat", 10, 0, 1.5, 1.5, False],

    ["Evade", "combat", 5, 0, 1.5, 1.5, False],
    ["Draw Weapon", "combat", -2, -2, 1.5, 1.5, False],
    ["Reload", "combat", -2, -2, 1.5, 1.5, False],

    ["Observe", "general", 10, 0, 1.5, 1.5, False],

    ["Cast", "astral", -2, -2, 1.5, 1.5, False],

    ["Sustain", "astral", -2, -2, 1.5, 1.5, True],

    ["Matrix Action", "matrix", -2, -2, 1.5, 1.5, False],
]

matrix_attributes = [
    ["name", "description"],
    ["Processor", "Raw processing power"],
    ["System", "System quality"],
    ["Firewall", "Ability to resist illegal action"],
    ["Uplink", "Maximal bandwidth and latency"],
    ["Signal", "Strength of wireless signal"],
]

programmes = [
    ["name", "skill", "attribute"],
    ["Search", "Data Search", "Processor"],
    ["Stealth", "Cracking", "System"],
    ["Redirect", "Cracking", "System"],
    ["Scan", "Electronics", "Signal"],
    ["Jam", "Electronic Warfare", "Signal"],
    ["Analyze", "Computer Use", "System"],
    ["Exploit", "Cracking", "System"],
    ["Crypt", "Computer Use", "System"],
    ["Decrypt", "Decryption", "Processor"],
    ["Edit", "Computer Use", "System"],
    ["Find", "Computer Use", "System"],
    ["Corrupt", "Cybercombat", "Processor"],
]

programmes_nt = namedtuple('programme', ['id'] + programmes[0])
programmes_dict = OrderedDict([(entry[0], programmes_nt(*([i] + entry))) for i, entry in enumerate(programmes[1:])])

matrix_actions = [
    ["name", "program", "prequesite"],
    ["Find Node on the Matrix", "Find", "AID"],
    ["Find Node in Wireless Range", "Scan", ""],
    ["Find Process in Node", "Find", "Node Access"],
    ["Find File in Node", "Find", "Node Access"],
    ["Find Stream going through Node", "Find", "Node Access"],
    ["Find Stream in Wireless Range", "Scan", ""],
    ["Analyze Node", "Analyze", "Found Node"],
    ["Analyze Process", "Analyze", "Found Process"],
    ["Analyze File", "Analyze", "Found File"],
    ["Analyze Stream", "Analyze", "Found Stream"],
    ["Access Node", "", "Found Node"],
    ["Access Process", "", "Found Process"],
    ["Access File", "", "Found File"],
    ["Access Stream", "", "Found Stream"],
    ["Encrypt File", "Crypt", "File Access"],
    ["Decrypt File", "Crypt" "File Access, Key"],
    ["Decrypt File", "Decrypt", "File Access"],
    ["Encrypt Stream", "Crypt", "Stream Access"],
    ["Decrypt Stream", "Crypt" "Stream Access, Key"],
    ["Decrypt Stream", "Decrypt", "Stream Access"],
    ["Modify Account", "", "Admin Access"],
    ["Modify Subscription List", "", "Logged into Node"],
    ["Modify Logfile", "", "Logged into Node"],
    ["Modify Process Account", "", "Logged into Process"],
    ["Edit File", "Edit", "File Access"],
    ["Edit Stream", "Edit", "Stream Access"],
    ["Start/Stop Process", "", "Logged into Node"],
    ["Shutdown Node", "", "Logged into Node"],
    ["Change Alarm Status", "", "Logged into Node"],
    ["Create/Delete File", "", "Logged into Node"],
    ["Controll Running Programm", "", "Logged into Process"],
    ["Start/Stop Subprocess", "", "Logged into Process"],
    ["Modify Connections", "", "Logged into Node    "],
    ["Change Stream Path", "", "Logged into Relay Node"],
    ["Terminate Stream", "", "Logged into Relay Node"],
    ["Slow Node", "Corrupt", "Found Node"],
    ["Shutdown Node", "Corrupt", "Found Node"],
    ["Slow Process", "Corrupt", "Found Process"],
    ["Stop Process", "Corrupt", "Found Process"],
    ["Corrupt File", "Corrupt", "Found File"],
    ["Kill Stream", "Corrupt", "Found Stream"],
    ["Jam Stream", "Jam", "Stream in Signal Range"],
    ["Jack-Out", "", ""]
]

bodyparts = [
    ["name", "template", "parent", "weightfrac", "charismamodfrac", "agilityfrac", "coordinationfrac", "strengthfrac",
     "constitutionfrac"],
    ["Body", "human", None, 1., 100., 1., 1., 1., 1., ],
    ["Head", "human", "Body", 1 / 11., 0.25, 0., 0.1, 0., 0.1, ],
    ["Vertebrae", "human", "Head", 0.2, 0.5, 0., 0., 0., 0., ],
    ["Eyes", "human", "Head", 0.05, 0.15, 0., 0., 0., 0., ],
    ["Ears", "human", "Head", 0.05, 0.1, 0., 1., 0., 0., ],
    ["Olfactory System", "human", "Head", 0.05, 0.05, 0., 0., 0., 0., ],
    ["Tongue", "human", "Head", 0.05, 0.05, 0., 0., 0., 0., ],
    ["Skull Shell", "human", "Head", 0.6, 0.15, 0., 0., 0., 1., ],
    ["Upper Body", "human", "Body", 2 / 11., 0.15, 0.15, 0.0, 0.2, 0.3, ],
    ["Lungs", "human", "Upper Body", 0.1, 0.1, 0., 0., 0.0, 0.3, ],
    ["Heart", "human", "Upper Body", 0.1, 0.2, 0., 0., 0.0, 0.2, ],
    ["* Muscles", "human", "Upper Body", 0.3, 0.3, 0.4, 0.2, 0.9, 0.3, ],
    ["* Bones", "human", "Upper Body", 0.5, 0.2, 0., 0., 0.1, 0.2, ],
    ["* Nerves", "human", "Upper Body", 0., 0.2, 0.6, 0.8, 0., 0., ],
    ["Lower Body", "human", "Body", 2 / 11., 0.15, 0.05, 0.0, 0.05, 0.1, ],
    ["Intestines", "human", "Lower Body", 0.4, 0.3, 0.0, 0.0, 0.0, 0.3, ],
    ["* Muscles", "human", "Lower Body", 0.3, 0.3, 0.4, 0.2, 0.9, 0.2, ],
    ["* Bones", "human", "Lower Body", 0.3, 0.2, 0., 0., 0.1, 0.5, ],
    ["* Nerves", "human", "Lower Body", 0., 0.2, 0.6, 0.8, 0., 0., ],
    ["Left Arm", "human", "Body", 1 / 11., 0.125, 0.2, 0.3, 0.175, 0.1, ],
    ["* Muscles", "human", "Left Arm", 0.6, 0.4, 0.4, 0.2, 0.9, 0.5, ],
    ["* Bones", "human", "Left Arm", 0.4, 0.2, 0., 0., 0.1, 0.5, ],
    ["* Nerves", "human", "Left Arm", 0., 0.4, 0.6, 0.8, 0., 0., ],
    ["Right Arm", "human", "Body", 1 / 11., 0.125, 0.2, 0.3, 0.175, 0.1, ],
    ["* Muscles", "human", "Right Arm", 0.6, 0.4, 0.4, 0.2, 0.9, 0.5, ],
    ["* Bones", "human", "Right Arm", 0.4, 0.2, 0., 0., 0.1, 0.5, ],
    ["* Nerves", "human", "Right Arm", 0., 0.4, 0.6, 0.8, 0., 0., ],
    ["Left Leg", "human", "Body", 2 / 11., 0.1, 0.2, 0.15, 0.2, 0.15, ],
    ["* Muscles", "human", "Left Leg", 0.6, 0.4, 0.4, 0.2, 0.9, 0.5, ],
    ["* Bones", "human", "Left Leg", 0.4, 0.2, 0., 0., 0.1, 0.5, ],
    ["* Nerves", "human", "Left Leg", 0., 0.4, 0.6, 0.8, 0., 0., ],
    ["Right Leg", "human", "Body", 2 / 11., 0.1, 0.2, 0.15, 0.2, 0.15, ],
    ["* Muscles", "human", "Right Leg", 0.6, 0.4, 0.4, 0.2, 0.9, 0.5, ],
    ["* Bones", "human", "Right Leg", 0.4, 0.2, 0., 0., 0.1, 0.5, ],
    ["* Nerves", "human", "Right Leg", 0., 0.4, 0.6, 0.8, 0., 0., ],
]

bodyparts_nt = namedtuple('bodypart', ['id'] + bodyparts[0])
replace_stars(bodyparts)
bodyparts_dict = OrderedDict([(entry[0], bodyparts_nt(*([i] + entry))) for i, entry in enumerate(bodyparts[1:])])

gameitems = [
    ["name", "clas", "availability", "cost", "weight", "vis_stealth", "scan_stealth", "legality"],
    ["Light Pistol", "Ranged Weapon", 20, 500, 0.6, 40, 20, 50],
    ["Heavy Pistol", "Ranged Weapon", 25, 1200, 2.0, 30, 15, 40],
    ["Machine Pistol", "Ranged Weapon", 25, 1200, 1.5, 30, 15, 40],
    ["Sub-Machine-Gun", "Ranged Weapon", 25, 1200, 3.0, 20, 10, 30],
    ["Shotgun", "Ranged Weapon", 25, 1200, 4.0, 30, 15, 40],
    ["Heavy Calibre Assault Rifle", "Ranged Weapon", 25, 1200, 4.0, 20, 10, 30],
    ["Assault Rifle", "Ranged Weapon", 25, 1200, 3.5, 20, 10, 30],
    ["Sniper Rifle", "Ranged Weapon", 25, 1200, 3.5, 20, 10, 30],
    ["Light MG", "Ranged Weapon", 25, 1200, 6.5, 20, 10, 30],
    ["Medium MG", "Ranged Weapon", 25, 1200, 10.0, 20, 10, 30],
    ["Heavy MG", "Ranged Weapon", 25, 1200, 30.0, 20, 10, 30],
    ["Armored Clothing", "Armor", 8, 500, 2.0, 25, 15, 0],
    ["Explorer Jumpsuit", "Armor", 8, 500, 4.0, 25, 15, 0],
    ["Flak Vest", "Armor", 10, 1000, 3.0, 20, 15, 0],
    ["Flak Vest with Plates", "Armor", 10.0, 3000, 6.0, 20, 15, 0],
    ["Lined Coat", "Armor", 8, 1500, 4.0, 25, 15, 0],
    ["Light Carapace", "Armor", 8, 5000, 8.0, 25, 15, 0],
    ["Heavy Carapace", "Armor", 8, 10000, 14.0, 25, 15, 0],
    ["Form Fitting Body Armor", "Armor", 8, 5000, 4.0, 25, 15, 0],
    ["Radio Shack 0815", "Cyberdeck", 1, 100, 0.05, 60, 40, 0],
    ["Renraku Hackset", "Cyberdeck", 20, 10000, 2.0, 10, 10, 0],
    ["Fairlight Excalibur", "Cyberdeck", 1, 100, 0.05, 60, 40, 0],
    ["Tower", "Cyberdeck", 20, 10000, 2.0, 10, 10, 0],
    ["Mainframe", "Cyberdeck", 1, 100, 0.05, 60, 40, 0],
    ["Cluster", "Cyberdeck", 20, 10000, 2.0, 10, 10, 0],
]

gameitems_nt = namedtuple('gameitem', ['id'] + gameitems[0])
gameitems_dict = OrderedDict([(entry[0], gameitems_nt(*([i] + entry))) for i, entry in enumerate(gameitems[1:])])

rangedweapons = [
    ["item", "skillclass", "skillmod", "damage", "damagetype", "penetration", "range", "shot", "burst", "auto",
     "minstr", "recoil", "mag", "magtype", "top", "under", "barrel", "special"],
    ["Heavy Pistol", "Pistols", 0., 16., "ballistic", 8., 12., 5, 0, 0, 50, 30, 10, "", 1, 0, 1, None],
    ["Light Pistol", "Pistols", 0., 8., "ballistic", 4., 10., 6, 0, 0, 30, 15, 15, "", 0, 0, 1, None],
    ["Machine Pistol", "Automatics", 0., 8., "ballistic", 4., 10, 6, 12, 18, 40, 15, 20, "", 1, 0, 1, None],
    ["Sub-Machine-Gun", "Automatics", 0., 8., "ballistic", 4., 20, 6, 15, 30, 20, 7, 30, "", 1, 0, 1, None],
    ["Shotgun", "Long Rifle", 0., 40., "ballistic", 4., 20, 5, 0, 0, 40, 15, 6, "", 1, 1, 1, None],
    ["Heavy Calibre Assault Rifle", "Automatics", 0., 18., "ballistic", 12., 100, 4, 10, 20, 54, 20, 20, "", 1, 1, 1,
     None],
    ["Assault Rifle", "Automatics", 0., 12., "ballistic", 8., 80, 5, 12, 18, 36, 12, 30, "", 1, 1, 1, None],
    ["Sniper Rifle", "Long Rifles", 0., 18., "ballistic", 12., 160, 2, 0, 0, 60, 15, 10, "", 1, 1, 1, None],
    ["Light MG", "Automatics", 0., 12., "ballistic", 8., 120, 2, 20, 40, 60, 10, 100, "", 1, 1, 1, None],
    ["Medium MG", "Automatics", 0., 18., "ballistic", 12., 150, 1, 20, 40, 80, 15, 100, "", 1, 1, 1, None],
    ["Heavy MG", "Automatics", 0., 60., "ballistic", 40., 300, 1, 30, 50, 180, 25, 100, "", 1, 1, 1, None],
]

armor = [
    ["item", "locations", "maxagi", "coordmult", "ballistic", "impact"],
    ["Armored Clothing", ["Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     60, 0.95, 10., 0.],
    ["Explorer Jumpsuit", ["Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     70, 0.90, 10., 20.],
    ["Flak Vest", ["Upper Body", "Lower Body"],
     60, 0.9, 30., 20.],
    ["Flak Vest with Plates", ["Upper Body", "Lower Body"],
     50, 0.85, 50., 40.],
    ["Form Fitting Body Armor", ["Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     50, 0.9, 25., 5.],
    ["Lined Coat", ["Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     50, 0.9, 20., 0.],
    ["Light Carapace", ["Head", "Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     40, 0.8, 40., 30.],
    ["Heavy Carapace", ["Head", "Upper Body", "Lower Body", "Right Arm", "Left Arm", "Right Leg", "Left Leg"],
     30, 0.75, 50., 40.],
]

ware = [
    ["name", "kind", "charismamod", "part_weight", "additional_weight", "desc", "basecost", "cost", "parts", "effects",
     "location"],
    ["Left Cyberarm", "cyberware", 0, 0, 0, "Artificial cyberlimb", 500, 500, ["Left Arm"], [], ''],
    ["Right Cyberarm", "cyberware", 0, 0, 0, "Artificial cyberlimb", 500, 500, ["Right Arm"], [], ''],
    ["Left Cyberleg", "cyberware", 0, 0, 0, "Artificial cyberlimb", 500, 500, ["Left Leg"], [], ''],
    ["Right Cyberleg", "cyberware", 0, 0, 0, "Artificial cyberlimb", 500, 500, ["Right Leg"], [], ''],
    ["Muscle Augmentation Upper", "bioware", 0, 0, 0, "Biological muscle replacement", 1000, 0,
     ["Left Arm Muscles", "Right Arm Muscles", "Upper Body Muscles"], [], ''],
    ["Muscle Augmentation Lower", "bioware", 0, 0, 0, "Biological muscle replacement", 1000, 0,
     ["Left Leg Muscles", "Right Leg Muscles", "Lower Body Muscles"], [], ''],
    ["Muscle Augmentation Total", "bioware", 0, 0, 0, "Biological muscle replacement", 1000, 0,
     ["Left Leg Muscles", "Right Leg Muscles", "Lower Body Muscles",
      "Left Arm Muscles", "Right Arm Muscles", "Upper Body Muscles"], [], ''],
    ["Muscle Replacement Upper", "cyberware", 0, 0, 0, "Cybernetic muscle replacement", 1000, 0,
     ["Left Arm Muscles", "Right Arm Muscles", "Upper Body Muscles"], [], ''],
    ["Muscle Replacement Lower", "cyberware", 0, 0, 0, "Cybernetic muscle replacement", 1000, 0,
     ["Left Leg Muscles", "Right Leg Muscles", "Lower Body Muscles"], [], ''],
    ["Muscle Replacement Total", "cyberware", 0, 0, 0, "Cybernetic muscle replacement", 1000, 0,
     ["Left Leg Muscles", "Right Leg Muscles", "Lower Body Muscles",
      "Left Arm Muscles", "Right Arm Muscles", "Upper Body Muscles"], [], ''],
    ["Wired Reflexes I", "cyberware", 0, 0, 0, "Cybernetic nerve replacement", 1000, 5000,
     ["Vertebrae"], [["stats", "Combat Awareness", "*0.8"]], ''],
    ["Wired Reflexes II", "cyberware", 0, 0, 0, "Cybernetic nerve replacement", 3000, 150000,
     ["Vertebrae", "Upper Body Nerves", "Left Arm Nerves", "Right Arm Nerves"],
     [["stats", "Combat Awareness", "*0.65"]], ''],
    ["Wired Reflexes III", "cyberware", 0, 0, 0, "Cybernetic nerve replacement", 9000, 45000,
     ["Vertebrae", "Upper Body Nerves", "Left Arm Nerves", "Right Arm Nerves", "Lower Body Nerves", "Left Leg Nerves",
      "Right Leg Nerves"],
     [["stats", "Combat Awareness", "*0.5"]], ''],
    ["Synaptic Accelerator I", "bioware", 0, 0, 0, "Bionetic nerve replacement", 1500, 7500,
     ["Vertebrae"], [["stats", "Combat Awareness", "*0.8"]], ''],
    ["Synaptic Accelerator II", "bioware", 0, 0, 0, "Bionetic nerve replacement", 5000, 25000,
     ["Vertebrae", "Upper Body Nerves", "Left Arm Nerves", "Right Arm Nerves"],
     [["stats", "Combat Awareness", "*0.65"]], ''],
    ["Synapti Accelerator III", "bioware", 0, 0, 0, "Bionetic nerve replacement", 22000, 110000,
     ["Vertebrae", "Upper Body Nerves", "Left Arm Nerves", "Right Arm Nerves", "Lower Body Nerves", "Left Leg Nerves",
      "Right Leg Nerves"],
     [["stats", "Combat Awareness", "*0.5"]], ''],
    ["Encephalon I", "cyberware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 5000, [], [["attributes", "Logic", "+10"]], ''],
    ["Encephalon II", "cyberware", 0, 10, 0, "Cybernetic Coprocessor", 5000, 15000, [], [["attributes", "Logic", "+20"]], ''],
    ["Encephalon III", "cyberware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 45000, [], [["attributes", "Logic", "+30"]], ''],
    ["Thalamus Enhancer I", "cyberware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 5000, [], [["attributes", "Intuition", "+10"]], ''],
    ["Thalamus Enhancer II", "cyberware", 0, 10, 0, "Cybernetic Coprocessor", 5000, 15000, [], [["attributes", "Intuition", "+20"]], ''],
    ["Thalamus Enhancer III", "cyberware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 45000, [], [["attributes", "Intuition", "+30"]], ''],
    ["Lymbic Filter I", "cyberware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 5000, [], [["attributes", "Willpower", "+10"]], ''],
    ["Lymbic Filter II", "cyberware", 0, 10, 0, "Cybernetic Coprocessor"  , 5000, 15000, [], [["attributes", "Willpower", "+20"]], ''],
    ["Lymbic Filter III", "cyberware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 45000, [], [["attributes", "Willpower", "+30"]], ''],
    ["Cerebral Booster I", "bioware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 7500, [], [["attributes", "Logic", "+10"]], ''],
    ["Cerebral Booster II", "bioware", 0, 10, 0, "Cybernetic Coprocessor", 5000, 25000, [], [["attributes", "Logic", "+20"]], ''],
    ["Cerebral Booster III", "bioware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 110000, [], [["attributes", "Logic", "+30"]], ''],
    ["Biological Intuition I", "bioware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 7500, [], [["attributes", "Intuition", "+10"]], ''],
    ["Biological Intuition II", "bioware", 0, 10, 0, "Cybernetic Coprocessor", 5000, 25000, [], [["attributes", "Intuition", "+20"]], ''],
    ["Biological Intuition III", "bioware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 110000, [], [["attributes", "Intuition", "+30"]], ''],
    ["Biological Willpower I", "bioware", 0, 5, 0, "Cybernetic Coprocessor", 5000, 7500, [], [["attributes", "Willpower", "+10"]], ''],
    ["Biological Willpower II", "bioware", 0, 10, 0, "Cybernetic Coprocessor", 5000, 25000, [], [["attributes", "Willpower", "+20"]], ''],
    ["Biological Willpower III", "bioware", 0, 15, 0, "Cybernetic Coprocessor", 5000, 110000, [], [["attributes", "Willpower", "+30"]], ''],
]

ware_nt = namedtuple('bodypart', ['id'] + ware[0])
ware_dict = OrderedDict([(entry[0], ware_nt(*([i] + entry))) for i, entry in enumerate(ware[1:])])

cyberdecks = [
    ["item", "processor", "system", "uplink", "signal"],
    ["Radio Shack 0815", 5, 20, 10, 30],
    ["Renraku Hackset", 30, 30, 30, 30],
    ["Fairlight Excalibur", 60, 60, 60, 60],
    ["Tower", 30, 30, 60, 0],
    ["Mainframe", 40, 20, 60, 0],
    ["Cluster", 100, 30, 100, 0],
]

cyberdecks = [["item", "attribute", "rating"]] + [j for i in cyberdecks[1:] for j in
                                                  [[i[0], "Processor", i[1]], [i[0], "System", i[2]],
                                                   [i[0], "Uplink", i[3]], [i[0], "Signal", i[4]]]]

spells = [
    ['name', 'category', 'subcategoy', 'threshold', 'resist', 'drain', 'effekt', 'range', 'volume', 'anchor',
     'casttime'],
    ['Mana Bolt',
     'Mana, Mind',
     'destruction',
     '10',
     'Willpower',
     'X',
     'X% Damage',
     '64m',
     '1 Target',
     '-',
     '3'],
    ['Power Bolt',
     'Mana, Body',
     'destruction',
     '0',
     'Body',
     'X',
     'X% Damage',
     '128m',
     '1 Target',
     '-',
     '2'],
    ['Fireball',
     'Physical',
     'destruction',
     '30',
     'Dodge',
     'X+Y',
     'X Damage, Y/5 Penetration, burn, nostage',
     '32m',
     '2m',
     '-',
     '5'],
    ['Firebolt',
     'Physical',
     'destruction',
     '20',
     'Dodge',
     'X+Y',
     'X Damage, Y/2 Penetration',
     '64m',
     '1 Target',
     '-',
     '3'],
]
